# Generated by Django 5.0.4 on 2024-04-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employer',
            new_name='is_employee',
        ),
    ]
