# Generated by Django 5.0.4 on 2024-04-22 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('rating', models.CharField(choices=[('G', 'General audiences'), ('PG', 'Parental guidance suggested'), ('PG-13', 'Parents strongly cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default='G', max_length=20)),
                ('synopsis', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
