# Generated by Django 4.2.2 on 2023-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movies_user',
            new_name='buyers',
        ),
        migrations.RenameField(
            model_name='movieorder',
            old_name='user',
            new_name='buyer',
        ),
    ]
