# Generated by Django 4.2 on 2023-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_added_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(default=None, null=True),
        ),
    ]
