# Generated by Django 5.0.4 on 2024-04-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, choices=[('G', 'General audiences'), ('PG', 'Parental guidance suggested'), ('PG-13', 'Parents strongly cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default='G', max_length=20),
        ),
    ]
